### PR TITLE
[MAINTENANCE] Added additional repository functional test instead of unit tests.

### LINKED ISSUE #781: [FUND] Add tests and significantly improve test coverage
## Description

Currently Kitodo.Presentation barely has any (unit) tests, so implementing new features and making sure that nothing broke is very tedious and time consuming - not only for developers but for the release management as well. This proposal suggests to write a lot of tests and significantly improve test coverage for Kitodo.Presentation.

## Related Issues

None.

## Expected Benefits of this Development

Test-driven development ensures that developing new features, updating components or re-factoring code doesn't break anything (or at least makes obvious what broke). This is especially important for older projects with a large and complex code base, since it's impossible for a single developer to know every constraint and dependency.
Having tests would therefor improve code quality, make development easier and help testing and reviewing pull requests for the release management.

## Estimated Costs and Complexity

Writing tests is not a complex, but a rather time-consuming task, so I'd estimate this to be of **high** cost and **low** complexity.

### PR DESCRIPTION
**Pull request by haogatyp**
Instead of unit testing repositories it is recommended to do functional tests.

### CODE REVIEW

**Comment by sebastian-meyer** [comment]
Could you please bring this pull request up to date with master? Alternatively you can allow me to update your branch, then I can do it myself via GitHub most of the time.

**Comment by haogatyp** [comment]
I did a rebase on the current master.

**Comment by oliver-stoehr** [comment]
@sebastian-meyer we have to remove the temporary file in TokenRepositoryTest.php:46, but according to Codacy
`The use of function shell_exec() is forbidden` and
`The use of function unlink() is discouraged`. 
Do you see any other way to remove the file or should I use `unlink` as it is "just" discouraged?
(I will fix the other Codacy issues.)

**Comment by sebastian-meyer** [comment]
Yes, please revert this back to `unlink()`, since this is more portable than `shell_exec()` (which only works on UNIX and is disabled on many shared hosting services for security reasons). I'll then look into which rule actually discourages using `unlink()` and how to make an exception in this case.

**Review by sebastian-meyer — APPROVED** [review]

**Pull request merged**
