### PR TITLE
ListView: add called collection

### PR DESCRIPTION
**Pull request by BFallert**
idea from @michaelkubina
see: https://github.com/kitodo/kitodo-presentation/issues/918

When a collection is called in a collection list (Kitodo:Collection), a ListView is called. In this ListView it is desirable to be able to output the name of the selected collection (Headline) and its associated data (Thumbnail and Description).

With these adjustments this is possible without further configuration.

### CODE REVIEW

**Comment by BFallert** [comment]
Was not sure which branch to take master or 4.x.

**Comment by csidirop** [comment]
I think all PRs going to master, and master is merged at regular intervals into 4.x

**Comment by sebastian-meyer** [comment]
Please have a look at [Resources/Private/Templates/Collection/List.html](https://github.com/kitodo/kitodo-presentation/blob/master/Resources/Private/Templates/Collection/List.html). This template already contains your proposed additions and is meant to be used with the `Collection` controller.

I am OK with unifying the templates and using only one template for all cases, but then we need to remove the duplicate template and make sure the unified template is always used.

**Comment by sebastian-meyer** [comment]
> I think all PRs going to master, and master is merged at regular intervals into 4.x

Yes, that's true until development of a new major version begins. Currently I am working on the 4.1 release, so all pull requests should still target the `master` branch. After that the next version will be 5.0 (with support for TYPO3 v11) and any upcoming changes to 4.1 should then be targeted at the `4.x` branch.

**Comment by sebastian-meyer** [comment]
How should we proceed with this pull request, @BFallert?

**Comment by BFallert** [comment]
> Please have a look at [Resources/Private/Templates/Collection/List.html](https://github.com/kitodo/kitodo-presentation/blob/master/Resources/Private/Templates/Collection/List.html). This template already contains your proposed additions and is meant to be used with the Collection controller.

But when i clicked on a collection on a page that contains a collection list (plugin: Collection), a normal ListView is called.

> I am OK with unifying the templates and using only one template for all cases, but then we need to remove the duplicate template and make sure the unified template is always used.

Small adjustments would probably still have to be made in the existing template. 
But I don't know how I can call up the same template from two different situations (collection and listView)?
Can anyone offer support here? 

On the other hand, if I'm the only one with this problem, we can close the PR.

**Comment by sebastian-meyer** [comment]
> On the other hand, if I'm the only one with this problem, we can close the PR.

**Pull request closed without merging**
