### PR TITLE
Highlight exact word

### PR DESCRIPTION
**Pull request by beatrycze-volk**
DDB has reported that highlight of the found word includes words which should not be there. 

Example:
`the` will highlight also '**the**ir', '**the**y' or '**The**odore'.

Depends on #588

### CODE REVIEW

**Review by albig — CHANGES_REQUESTED** [review]
Actually the code seems works like before. That's very good.

I used
* pageview 
* fulltext active
* searchInDocument

--> The word is highlighted.

If I change the TypoScript

```
plugin.tx_dlf_fulltexttool.searchHlElements = tx_dlf[highlight_word],tx_dlf[query],tx_dlf[another]
```

It still works for the default `tx_dlf[highlight_word]` parameter. If I add `tx_dlf[other]`, this doesn't  highlight. Only if `tx_dlf[highlight_word]` is missing. That's what you wrote in #588.

But is there any usage of another highlighting search element in the current Kitodo.Presentation? I do not get the point. Sorry ;-)

And if so, shouldn't we write some sentence to explain this setting / feature?

**Comment by beatrycze-volk** [comment]
_It still works for the default tx_dlf[highlight_word] parameter. If I add tx_dlf[other], this doesn't highlight. Only if tx_dlf[highlight_word] is missing. That's what you wrote in #588._

 The first defined param on the configuration has highest priority, if not found it checks next ones.
 So in this case the param from search in the document has highest priority and search word from hit list has the second priority.

_But is there any usage of another highlighting search element in the current Kitodo.Presentation?_

No idea ;) IN DDB they use it in the way that if the newspaper is open from list of found results it highlights the search term which uses param 'query' and search in document uses different param to distinguish those two searches.

**Comment by albig** [comment]
> _But is there any usage of another highlighting search element in the current Kitodo.Presentation?_
> 
> No idea ;) IN DDB they use it in the way that if the newspaper is open from list of found results it highlights the search term which uses param 'query' and search in document uses different param to distinguish those two searches.

With the configuration
```
plugin.tx_dlf_fulltexttool.searchHlElements = query,tx_dlf[highlight_word]
```

The flow would be

1. launch the pageview (from some listing outside) with e.g. `&query=Dresden` --> `Dresden` will be highlighted.
2. search in document inside the pageview --> `&tx_dlf[highlight_word]=Leipzig` --> `Leipzig` will be highlighted. But `Dresden` won't anymore.

You cannot highlight both and there is no use case for this, right?

If I understand this right, this feature doesn't hurt Kitodo.Presentation but also does not bring any advantage for itself. So we could merge it, if you just confirm my assumptions and add the explanation in your comment to the documentation.

**Comment by beatrycze-volk** [comment]
_You cannot highlight both and there is no use case for this, right?_

Exactly so.

_If I understand this right, this feature doesn't hurt Kitodo.Presentation but also does not bring any advantage for itself. So we could merge it, if you just confirm my assumptions and add the explanation in your comment to the documentation._

True, it almost doesn't bring anything new and also doesn't hurt. Default behavior is preserved.

**Comment by sebastian-meyer** [comment]
This pull request's title is _Highlight exact word_ and its description suggests that it's about highlighting whole words only instead of highlighting matching parts of a word as well. But all you are talking about is using different URL parameters for highlighting. I am confused...

What is this pull request really about? Does this pull request contain both changes? If yes, does it supersede #588 then?

Regarding the original intentions of highlighting only whole words: I don't think this is a good idea. Especially in the German language there are a lot of composed words and grammatical forms which wouldn't be highlighted anymore. Someone searching for e. g. "Dresden" would certainly want to find "Dresdens" or "Dresden-Klotzsche" as well. This should at least be configurable while preserving the current behaviour as default.

**Comment by beatrycze-volk** [comment]
_This pull request's title is Highlight exact word and its description suggests that it's about highlighting whole words only instead of highlighting matching parts of a word as well. But all you are talking about is using different URL parameters for highlighting. I am confused..._

_What is this pull request really about? Does this pull request contain both changes? If yes, does it supersede #588 then?_

It contains also changes from previous PR, this one is only about highlighting exact words.

_Regarding the original intentions of highlighting only whole words: I don't think this is a good idea. Especially in the German language there are a lot of composed words and grammatical forms which wouldn't be highlighted anymore. Someone searching for e. g. "Dresden" would certainly want to find "Dresdens" or "Dresden-Klotzsche" as well. This should at least be configurable while preserving the current behaviour as default._

It was exactly what was expectation from Zeitungsportal. They expect that only exact word will be higlighted, not part of the words. What should be doing in that case? Should this change be only for them and not introduced here or maybe should be used parameter which lets decide about type of higlight (e.g. exactHighlight true or false)?

**Comment by sebastian-meyer** [comment]
> It contains also changes from previous PR, this one is only about highlighting exact words.

OK, so #588 should be merged before this one. 👍🏼 

> It was exactly what was expectation from Zeitungsportal. They expect that only exact word will be higlighted, not part of the words. What should be doing in that case? Should this change be only for them and not introduced here or maybe should be used parameter which lets decide about type of higlight (e.g. exactHighlight true or false)?

I'd prefer the former: Since this change makes highlighting behave different then searching, I think it's a special case for the Zeitungsportal and shouldn't be introduced here. IMHO users would be confused if they get a hit searching for e. g. "Dresden", but then don't see anything highlighted because of the strict matching. On the other hand: maintaining a separate fork just for the DDB is a pain in the a**, too. @albig: What do you think?

**Comment by beatrycze-volk** [comment]
@sebastian-meyer we have special extenstion for them, all changes which are not matching here, are introduced there.

**Comment by sebastian-meyer** [comment]
> @sebastian-meyer we have special extenstion for them, all changes which are not matching here, are introduced there.

Yes, but is there a way to introduce this change there without forking the whold `PageView` plugin?

**Comment by beatrycze-volk** [comment]
@sebastian-meyer we are replacing there JS files and pass them as an one file.

**Comment by sebastian-meyer** [comment]
OK, so when it's fine with you, I'd suggest to keep this out of Kitodo.Presentation.

**Pull request closed without merging**
