### PR TITLE
Improve fulltext and image manipulation tool

### PR DESCRIPTION
**Pull request by jacmendt**
Beside some code reorganization and refactoring as well as some minor changes the main features are listed below:
- Replaces the ol.format.Alto through a jquery based ALTO parser (tx_dlf_altoparser.js)
- Upgrade to OpenLayers 3.15.1
- Uses [glif-library](https://github.com/slub/webgl-image-filter) for image manipulation through remove of functionality from the OpenLayers library.
- Allows highlighting of words in fulltext mode through passing a list of words via query parameters in the style `tx_dlf[highlight_word]=Sachsen;lebens`
- Introducing of a `npm` and `karma` based testing environment for javascript functions

### CODE REVIEW

**Comment by albig** [comment]
Your code is now working on our staging system [test.digital.slub-dresden.de](http://test.digital.slub-dresden.de).

**Comment by stweil** [comment]
@albig, your staging system crashed some minutes ago when I was searching for newspapers. It told me to inform you...

I'm still looking for examples which use the newspaper code.

**Comment by jacmendt** [comment]
I fixed a bug and allow the highlight to be used also in case fulltext is deactivate.

**Comment by jacmendt** [comment]
I fixed a couple of bugs and allowed word highlighting also in case of double page view-

**Pull request merged**
