### PR TITLE
[SECURITY] Update dependencies to fix security issues

### PR DESCRIPTION
**Pull request by sebastian-meyer**
This updates all dependencies to the latest versions still supporting PHP 7.4. It addresses the [security advisories published by TYPO3](https://typo3.org/help/security-advisories/security).

### CODE REVIEW

**Comment by stweil** [comment]
A local installation on Ubuntu 20.04 fails:
```
root@c9e7192fc97c:~/kitodo-presentation# composer create-project
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for typo3/cms-core v11.5.35 -> satisfiable by typo3/cms-core[v11.5.35].
    - typo3/cms-core v11.5.35 requires composer-runtime-api ^2.1 -> no matching package found.
  Problem 2
    - typo3/cms-core v11.5.35 requires composer-runtime-api ^2.1 -> no matching package found.
    - typo3/testing-framework 6.16.9 requires typo3/cms-core 10.*.*@dev || 11.*.*@dev -> satisfiable by typo3/cms-core[v11.5.35].
    - Installation request for typo3/testing-framework 6.16.9 -> satisfiable by typo3/testing-framework[6.16.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by stweil** [comment]
The  local installation on Ubuntu 20.04 works after removing `composer.lock`.

**Comment by sebastian-meyer** [comment]
It looks like you are using an older composer version. TYPO3v11 requires composer v2.1 or newer.

I tried this locally as well and don't get any errors when using composer 2.1.

**Review by stweil — COMMENTED** [review]
A local installation on Ubuntu 20.04 fails with the provided `composer.lock`, but works without it.

**Comment by sebastian-meyer** [comment]
Could you please send me the `composer.lock` file you get after a successful installation? I'd like to compare that to my `composer.lock`.

**Comment by stweil** [comment]
@sebastian-meyer, Ubuntu 20.04 installs composer 2.2.6-2ubuntu4.

**Comment by stweil** [comment]
@sebastian-meyer, see ZIP file: [composer.zip](https://github.com/kitodo/kitodo-presentation/files/14278920/composer.zip)

**Comment by sebastian-meyer** [comment]
That's really curious, because that `composer.lock` is exactly the same as the one in this pull request... I checked with `diff` and it returns no differences.

**Comment by stweil** [comment]
Strange, I see lots of differences, and `ls` also shows a different size (composer.lock- is the original one):
```
root@c9e7192fc97c:~/kitodo-presentation# ls -l composer.*
-rw-r--r-- 1 root root   3100 Feb 14 12:19 composer.json
-rw-r--r-- 1 root root 275524 Feb 14 12:19 composer.lock
-rw-r--r-- 1 root root 312041 Feb 14 11:10 composer.lock-
```

**Comment by sebastian-meyer** [comment]
OK, my fault. I was too dumb to use Powershell's `diff` command correctly... ;)

**Comment by sebastian-meyer** [comment]
> @sebastian-meyer, Ubuntu 20.04 installs composer 2.2.6-2ubuntu4.

Are you sure, you are using this composer version? The [official Ubuntu 20.04 package](https://packages.ubuntu.com/focal/composer) is 1.10.1-1, which does not meet the requirements for TYPO3v11 (`composer-runtime-api` in version 2.1+). That's why you can't install the given `composer.lock` dependencies. Instead your composer installs TYPO3v10 (`typo3/cms-core` in version 10.4.37), because that has no dependency to `composer-runtime-api`.

**Comment by stweil** [comment]
You are right. I am running two podman containers with Ubuntu 20.04 and 22.04 and had looked in the newer one. 20.04 uses composer 1.10.1-1.

**Comment by sebastian-meyer** [comment]
Unfortunately there is no way to provide two separate `composer.lock` for TYPO3v10 and v11 respectively. So I suggest keeping the `composer.lock` for the latest available versions. If somebody wants to use older releases (like TYPO3v10), they would need to use `composer update` instead of `composer install` or delete the `composer.lock` file before installing.
What do you think?

**Comment by sebastian-meyer** [comment]
I've added a `composer.lock-t3v10` which can be used if you want to install TYPO3v10 instead of v11.

**Comment by stweil** [comment]
Meanwhile most tests pass with TYPO3 v11 and Solarium 6.0.4:
```
$ composer test -- -p 8.2
> Build/Test/runTests.sh -s unit '-p' '8.2'
Creating network "dlf_testing_default" with the default driver
Creating dlf_testing_unit_run ... done
PHP 8.2.12 (cli) (built: Oct 28 2023 02:10:03) (NTS)
PHPUnit 9.6.16 by Sebastian Bergmann and contributors.

..............S                                                   15 / 15 (100%)

Time: 00:00.018, Memory: 8.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 15, Assertions: 71, Skipped: 1.
Removing dlf_testing_unit_run_17c1c9b9bcf9 ... done
Removing network dlf_testing_default

###########################################################################
Result of unit
PHP: 8.2
SUCCESS
###########################################################################

> Build/Test/runTests.sh -s functional '-p' '8.2'
Using driver: mysqli
Creating network "dlf_testing_default" with the default driver
Creating dlf_testing_mariadb_1 ... done
Creating dlf_testing_web_1     ... done
Creating dlf_testing_solr_1    ... done
Creating dlf_testing_functional_run ... done
Waiting for database start...
Database is up
Waiting for Solr start...
Solr is up
PHP 8.2.12 (cli) (built: Oct 28 2023 02:10:03) (NTS)
PHPUnit 9.6.16 by Sebastian Bergmann and contributors.

.....F..................................................          56 / 56 (100%)

Time: 00:18.692, Memory: 207.00 MB

There was 1 failure:

1) Kitodo\Dlf\Tests\Functional\Api\OaiPmhTest::noRecordsUntil1900
Failed asserting that exception of type "Phpoaipmh\Exception\MalformedResponseException" matches expected exception "Phpoaipmh\Exception\OaipmhException". Message was: "Could not decode XML Response: String could not be parsed as XML" at
/kitodo-presentation/vendor/caseyamcl/phpoaipmh/src/Client.php:134
/kitodo-presentation/vendor/caseyamcl/phpoaipmh/src/Client.php:95
/kitodo-presentation/vendor/caseyamcl/phpoaipmh/src/RecordIterator.php:224
/kitodo-presentation/vendor/caseyamcl/phpoaipmh/src/RecordIterator.php:190
/kitodo-presentation/vendor/caseyamcl/phpoaipmh/src/RecordIterator.php:326
/kitodo-presentation/Tests/Functional/Api/OaiPmhTest.php:179
.

FAILURES!
Tests: 56, Assertions: 263, Failures: 1.
ERROR: 1
Stopping dlf_testing_solr_1    ... done
Stopping dlf_testing_web_1     ... done
Stopping dlf_testing_mariadb_1 ... done
Removing dlf_testing_functional_run_aa9bbc6415bd ... done
Removing dlf_testing_solr_1                      ... done
Removing dlf_testing_web_1                       ... done
Removing dlf_testing_mariadb_1                   ... done
Removing network dlf_testing_default

###########################################################################
Result of functional
PHP: 8.2
DBMS: mariadb  version 10.3  driver mysqli
FAILURE
###########################################################################

Script Build/Test/runTests.sh -s functional handling the test:func event returned with error code 1
Script @test:func was called via test
```

**Review by stweil — APPROVED** [review]
Thanks!

**Pull request merged**
