### PR TITLE
Content Element Wizard support

### PR DESCRIPTION
**Pull request by erik-konrad**
* adds icon set in TYPO3 Backend icon style
* adds all Kitodo Presentation Plugins to own Tab in Content Element Wizard

### CODE REVIEW

**Review by sebastian-meyer — DISMISSED** [review]
Technically this is fine and ready for merging. But I'd like to hear some more opinions on the icons, some of which are not very intuitive (i.e. page grid, navigation, ...).

**Review by gnuj — CHANGES_REQUESTED** [review]
Most of the icons are well choosen. Great.

Just a few ideas right here:

**tx-dlf-basket.svg**
The bag is fine. I would remove the litte plus icon.

**tx-dlf-collection.svg**
I suggest a icon with a stack metaphor. Maybe three stacked pages or [something in this direction](https://thenounproject.com/search/?q=collection&i=2712583).

**tx-dlf-metadata.svg**
Maybe we could drop the browser frame?! 

**tx-dlf-navigation.svg**
Use a compass for this icon (navigation) and reuse this as icon for tx-dlf-pagegrid.svg

**tx-dlf-oaipmh.svg**
As far as i understand OAI-PMH a harvest or [nature metaphor](https://thenounproject.com/search/?q=harvest&i=1046415) might suit this a bit better. If this is not the case, just go with the pixelstyle font without the person.

**tx-dlf-pagegrid.svg**
Use the actual navigation icon from above. 

**tx-dlf-pageview.svg**
Just add some arrows (right and left) to the document icon to indicate the usage of this plugin.

**tx-dlf-tableofcontents.svg**
I suggest a icon that implies a [hierarchy](https://thenounproject.com/search/?q=table%20of%20contents&i=680641).

**Comment by erik-konrad** [comment]
All requested icons are revised now.

**Review by gnuj — APPROVED** [review]
Looks great. I'm happy with all the icons. 👍

**Review by sebastian-meyer — APPROVED** [review]

**Comment by sebastian-meyer** [comment]
Thank you very much for your contribution!

**Pull request merged**
