### PR TITLE
[BUGFIX] The function `errorAction()` needs to exists in `NewTenantController`

### PR DESCRIPTION
**Pull request by beatrycze-volk**
Without this function the backend module doesn't work

### CODE REVIEW

**Comment by sebastian-meyer** [comment]
I don't understand why there is a problem at all. `NewTenantController` extends `AbstractController` which extends Extbase's `ActionController` which in turn implements `ActionController::errorAction()`. So `NewTenantController` should've inherited this method. How can this function be missing?

**Comment by beatrycze-volk** [comment]
> I don't understand why there is a problem at all. `NewTenantController` extends `AbstractController` which extends Extbase's `ActionController` which in turn implements `ActionController::errorAction()`. So `NewTenantController` should've inherited this method. How can this function be missing?

I don't know but the fact is that without this function creation of the data in backend doesn't work. The error says that this function is missing. No other more detailed message was displayed.

**Comment by sebastian-meyer** [comment]
OK, but then the method should return the correct result type. Does something like `return parent::errorAction();` work? Otherwise we should at least return an empty response object to satisfy the interface.

**Comment by beatrycze-volk** [comment]
Changes in the last commit are working correctly with TYPO3 11.x (https://github.com/TYPO3/typo3/blob/629eb841ea8e92399bdccd63e80f2681510665bc/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php#L753), but with TYPO3 10.x there is an error because of incompatible return type (https://github.com/TYPO3/typo3/blob/808ef61a53bc1e7ef65b715c13727b0f2d086c24/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php#L650).

**Comment by sebastian-meyer** [comment]
The only difference seems to be that in TYPO3v10 the result of `getFlattenedValidationErrorMessage()` is returned directly, while in TYPO3v11 it's wrapped in `htmlResponse()`. Maybe we can distinguish those cases as well? Of course the return type then would have to be `string|ResponseInterface` (in PHPDocs) or `mixed` (in method signature), since PHP<8 doesn't support union types.

**Review by sebastian-meyer — APPROVED** [review]

**Comment by sebastian-meyer** [comment]
Since Codacy and PHPStan are fine with the current state, I am as well. ;o)

**Pull request merged**
