### PR TITLE
[FEATURE] Solr 9 compatibility

### PR DESCRIPTION
**Pull request by frank-ulrich-weber**

### CODE REVIEW

**Review by sebastian-meyer — DISMISSED** [review]

**Comment by sebastian-meyer** [comment]
@frank-ulrich-weber: Could you please adjust the tests to use the new Solr versions and config files?

**Comment by frank-ulrich-weber** [comment]
I'm not sure if the failed tests are a result of my changes within this pull request. I don't see the connection. Any hints on this?

**Comment by sebastian-meyer** [comment]
> I'm not sure if the failed tests are a result of my changes within this pull request. I don't see the connection. Any hints on this?

Yes, your changes seem to break the tests. Most (if not all) of the tests which utilize the Solr index are failing, so it's very likely that your changes caused this.

**Review by sebastian-meyer — APPROVED** [review]

**Comment by sebastian-meyer** [comment]
Thank you very much for debugging the testing issues and fixing them!

**Pull request merged**
