### PR TITLE
[MAINTENANCE] Fix OaiPmh functional tests

### PR DESCRIPTION
**Pull request by beatrycze-volk**
Remove slashes from search URLs - reason for failing tests:
```
Phpoaipmh\Exception\HttpException: Client error: `GET http://web:8000/public/typo3temp/var/tests/functional-3567482//index.php?id=20001&verb=Identify` resulted in a `404 Not Found` response
```

### CODE REVIEW

**Comment by sebastian-meyer** [comment]
Hm, all the URLs look good, now. Some of them are missing the `index.php` part, but that shouldn't be an issue. Do you have any idea why the tests still fail?

**Comment by beatrycze-volk** [comment]
> Hm, all the URLs look good, now. Some of them are missing the `index.php` part, but that shouldn't be an issue. Do you have any idea why the tests still fail?

I'm still searching the reason, but I'm starting to suspecting that somehow there is also a problem inside the preparation of the testing environment. I'm on checking out our code for inserting documents into the SOLR.

**Comment by sebastian-meyer** [comment]
Nice try! So it's a change in TYPO3 which breaks the tests...

**Comment by beatrycze-volk** [comment]
> Nice try! So it's a change in TYPO3 which breaks the tests...

Yes, but I'm still not able to pinpoint the place where the problem appears.

**Comment by sebastian-meyer** [comment]
Those are the only two commits since TYPO3 10.4.34 which IMHO could've caused our problem:

- https://github.com/typo3/typo3/commit/fa9832df37
- https://github.com/typo3/typo3/commit/5e1585ea79

**Review by sebastian-meyer — APPROVED** [review]
I have no idea why, but it works. Good job! ;o)

**Pull request merged**
