### PR TITLE
[BUGFIX] Fix parameter type for `$collections` in `CollectionController`

### LINKED ISSUE #1107: [BUG] Error in `CollectionController`
## Description

After #1069 my collection pages are no longer loading and giving this error:

`Uncaught TYPO3 Exception: Argument 1 passed to Kitodo\Dlf\Controller\CollectionController::processCollections() must be of the type array, object given, called in /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/CollectionController.php on line 104 | TypeError thrown in file /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/CollectionController.php in line 214.`

The ` $collections` Array gets overwritten by the return value of `collectionRepository->findAll()`:
https://github.com/kitodo/kitodo-presentation/blob/10248c53fd34bdd4bde3310a6bc8ccba46fe09d2/Classes/Controller/CollectionController.php#L97

Commenting out the line no longer causes the error, but no objects are loaded either.

Reverting the changes of #1069  is fixing the issue.

### PR DESCRIPTION
**Pull request by beatrycze-volk**
Fix for https://github.com/kitodo/kitodo-presentation/issues/1107

### CODE REVIEW

**Comment by csidirop** [comment]
I'm getting following error: ` Uncaught TYPO3 Exception: Cannot use object of type Kitodo\Dlf\Domain\Model\Collection as array | Error thrown in file /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/CollectionController.php in line 256`

**Comment by csidirop** [comment]
Not sure if this helps, but the error occurs regardless of whether the collections plugin points to a list plugin or a page plugin

**Comment by beatrycze-volk** [comment]
Weird, I have tested it by myself ad could without any problem display collection list and list of documents inside the collection.

**Comment by csidirop** [comment]
Interesting, can it be some differences in the configuration?

**Comment by beatrycze-volk** [comment]
That's possible - here is a ddev system which I have used to test those changes: https://github.com/slub/ddev-sachsendigital

**Comment by csidirop** [comment]
Tested again and have the same error (https://github.com/kitodo/kitodo-presentation/pull/1108#issuecomment-1845001029). I get this error regardless of whether the collection plugin calls the page view plugin directly or via separate list view.

https://github.com/kitodo/kitodo-presentation/blob/7432a44716dc7def6873d5218864dfcefae1c207/Classes/Controller/CollectionController.php#L256

Why do you think that `$collection` is an array? I cant follow you here.
I changed the call to `$key = ($collection->getPriority() * 1000) + random_int(0, 1000);` which fixes the issue here (for me).

With this change both collection pages are loading again. But again only the "indirect" one shows the correct result. The other one shows all indexed documents.

A var_dump of `$this->collection` in `SolrSearch::prepare()`:
https://github.com/kitodo/kitodo-presentation/blob/25639525814f0fcbf0b07d922314a563dd2cbe9f/Classes/Common/Solr/SolrSearch.php#L436
shows that the object is encapsulated in an array again for the one case. Comparable to https://github.com/kitodo/kitodo-presentation/issues/1106#issuecomment-1830325863

**Comment by beatrycze-volk** [comment]
> Why do you think that `$collection` is an array? I cant follow you here.

```
if ($this->settings['collections']) {
    $sortedCollections = [];
    foreach (GeneralUtility::intExplode(',', $this->settings['collections']) as $uid) {
        $sortedCollections[$uid] = $this->collectionRepository->findByUid($uid);
    }
    $collections = $sortedCollections;
} else {
    $collections = $this->collectionRepository->findAll();
}
```
Funxction `findByUid($uid)` returns `object|null`, but `findAll()` returns `QueryResultInterface|array`. So depending on the called function the returned collection can be `array` or `object` (it can be also `null` if doesn't exists).

**Comment by csidirop** [comment]
Okay right, thanks! So we can simply unify this so that an array is always used at this point? If `findByUid()` returns an object, just push it into an array.

**Comment by csidirop** [comment]
Can you tell me where `showAction()` is called from? I believe somewhere up the call stack will be a junction like your example where we get an object for one case and and array for the other case.

**Comment by beatrycze-volk** [comment]
> Can you tell me where `showAction()` is called from? I believe somewhere up the call stack will be a junction like your example where we get an object for one case and and array for the other case.

`showAction()` is called fromList.html template. There are 2 calls: https://github.com/kitodo/kitodo-presentation/blob/8fe3ca79f1af9e42974176365dc688c2bd01d7c0/Resources/Private/Templates/Collection/List.html#L20 and https://github.com/kitodo/kitodo-presentation/blob/8fe3ca79f1af9e42974176365dc688c2bd01d7c0/Resources/Private/Templates/Collection/List.html#L41

**Comment by beatrycze-volk** [comment]
> Okay right, thanks! So we can simply unify this so that an array is always used at this point? If `findByUid()` returns an object, just push it into an array.

I don't think that making such a conversion in this place makes sense. I would stay with the type check.

**Comment by csidirop** [comment]
Okay, then I can't find anything else to suggest. Is there anything else that you can think of?

**Comment by beatrycze-volk** [comment]
> Okay, then I can't find anything else to suggest. Is there anything else that you can think of?

Does it work for you with my type check or does the problem still appear?

**Comment by csidirop** [comment]
> > Okay, then I can't find anything else to suggest. Is there anything else that you can think of?
> 
> Does it work for you with my type check or does the problem still appear?

Unfortunately it still appears. Btw. I am trying to look into your sachsendigital ddev, but I have had a few problems so far.

**Comment by beatrycze-volk** [comment]
> > > Okay, then I can't find anything else to suggest. Is there anything else that you can think of?
> > 
> > 
> > Does it work for you with my type check or does the problem still appear?
> 
> Unfortunately it still appears.

In which line? Does it ignore the check for collection type?

**Comment by csidirop** [comment]
> In which line?

There is no error or exception anymore. It just shows all indexed documents again.

> Does it ignore the check for collection type?

If you are [referring to this check in `processCollections()`](https://github.com/beatrycze-volk/kitodo-presentation/blob/984ac7efebb106e38de0876676596ddde8d9aaac/Classes/Controller/CollectionController.php#L257), then no it does not ignore it. 
`processCollections()` is called six times (for my six collections?) and every time `$collection instanceof Collection` is true and the block is triggered. There is no run where nether the collection nor the array check is true.

**Comment by csidirop** [comment]
Not sure if that matters, but regardless whether I use the not-working "direct" or working "indirect" (with ListView) implementation, `$collection` is every time a `Collection` type.

But my [workaround ](https://github.com/kitodo/kitodo-presentation/issues/1106#issuecomment-1830325863) is still working. `showAction()` is only called in that "direct" implementation, while the "indirect" uses ListViewControllers `mainAction()`.

**Comment by csidirop** [comment]
I managed to reproduce this error in your ddev environment (with your fix-type branch):

collage

**Comment by beatrycze-volk** [comment]
Thank you for extensive testing! :)

As a summary:
With my change the error is not appearing but also the list of collections is not displayed, right? I will look into it and write you back.

**Comment by csidirop** [comment]
> As a summary: With my change the error is not appearing but also the list of collections is not displayed, right? I will look into it and write you back.

Right I think. The TYPO3 Exception is fixed. But the issue that ALL documents are shown instead of just the ones in the selected collection still exists (like before).

**Comment by beatrycze-volk** [comment]
@sebastian-meyer The issues https://github.com/kitodo/kitodo-presentation/issues/1106 and https://github.com/kitodo/kitodo-presentation/issues/1107 should be fixed by this changes but the problem of confusion between `collection` and `collections` in `SolrSearch` class should be tackled.

1. Should function `findSolrByCollection` search by no collection, one or many than maybe it should be renamed to `findSolrByCollections`? Or should we add to DocumentRepository second function and call one `findSolrByCollection` and second `findSolrByCollections`. First would take as parameter `Collection` object and second an `array` of `Collection` objects.
 
2. `$collection` attribute of `SolrSearch` class is clearly an array of collections. Should it be renamed to match its real use or was there some reason for this name?

**Review by csidirop — APPROVED** [review]
Collections working again for me. Also tested the search just in case, which works too.

Code looks good to me.

**Review by sebastian-meyer — APPROVED** [review]

**Pull request merged**
